name: "Setup"
description: "Setup tooling"
runs:
  using: "composite"
  steps:
    - name: Install dojoup
      run: curl -L https://install.dojoengine.org | bash
      shell: bash

    - name: Install dojo
      run: |
        dojoup --version ${{ env.DOJO_VERSION }}
      shell: bash
