name: "Setup"
description: "Setup tooling"
runs:
  using: "composite"
  steps:
    - name: Install dojoup
      run: curl -L https://install.dojoengine.org | bash
      shell: bash

    - name: Install dojo
      run: |
        /home/runner/.config/.dojo/dojoup/dojoup --version ${{ env.DOJO_VERSION }}
        sudo mv /home/runner/.config/.dojo/dojoup/sozo /usr/local/bin/
      shell: bash
