[package]
name = "tokens"
version = "0.1.0"
edition = "2024_07"

[dependencies]
openzeppelin_token = "1.0.0"
openzeppelin_introspection = "1.0.0"
openzeppelin_access = "1.0.0"
openzeppelin_upgrades = "1.0.0"
graffiti = { git = "https://github.com/rsodre/graffiti.git", rev = "url" }

[dev-dependencies]
cairo_test = "2.9.4"

[[target.starknet-contract]]
sierra = true
casm = false
