kind = "DojoModel"
class_hash = "0x62edd30e266fff7705231b334b0569efd8ccab6bf27695b6478f6827c3975dc"
original_class_hash = "0x62edd30e266fff7705231b334b0569efd8ccab6bf27695b6478f6827c3975dc"
abi = "manifests/dev/base/abis/models/game_center-Game-6a4ff15e.json"
tag = "game_center-Game"
qualified_path = "achievement::models::index::game"
manifest_name = "game_center-Game-6a4ff15e"

[[members]]
name = "world_address"
type = "felt252"
key = true

[[members]]
name = "namespace"
type = "felt252"
key = true

[[members]]
name = "published"
type = "bool"
key = false

[[members]]
name = "whitelisted"
type = "bool"
key = false

[[members]]
name = "total_karma"
type = "u16"
key = false

[[members]]
name = "name"
type = "ByteArray"
key = false

[[members]]
name = "description"
type = "ByteArray"
key = false

[[members]]
name = "torii_url"
type = "ByteArray"
key = false

[[members]]
name = "image_uri"
type = "ByteArray"
key = false

[[members]]
name = "owner"
type = "felt252"
key = false
