kind = "DojoModel"
class_hash = "0x1415bf897ef80681e233c6aa2b2a145340c3cbe71932337ef84ab284c5d6f"
original_class_hash = "0x1415bf897ef80681e233c6aa2b2a145340c3cbe71932337ef84ab284c5d6f"
abi = "manifests/dev/base/abis/models/game_center-AchievementCompletion-16a107b5.json"
tag = "game_center-AchievementCompletion"
qualified_path = "achievement::events::index::achievement_completion"
manifest_name = "game_center-AchievementCompletion-16a107b5"

[[members]]
name = "namespace"
type = "felt252"
key = true

[[members]]
name = "identifier"
type = "felt252"
key = true

[[members]]
name = "player_id"
type = "felt252"
key = true

[[members]]
name = "progress"
type = "u32"
key = false

[[members]]
name = "time"
type = "u64"
key = false
