kind = "DojoModel"
class_hash = "0x535e56e14f5c19117d153ad353efe78e4831b4926126c7783322f137509ca4c"
original_class_hash = "0x535e56e14f5c19117d153ad353efe78e4831b4926126c7783322f137509ca4c"
abi = "manifests/dev/base/abis/models/game_center-AchievementCreation-604e47bb.json"
tag = "game_center-AchievementCreation"
qualified_path = "achievement::events::index::achievement_creation"
manifest_name = "game_center-AchievementCreation-604e47bb"

[[members]]
name = "namespace"
type = "felt252"
key = true

[[members]]
name = "identifier"
type = "felt252"
key = true

[[members]]
name = "hidden"
type = "bool"
key = false

[[members]]
name = "points"
type = "u16"
key = false

[[members]]
name = "total"
type = "u32"
key = false

[[members]]
name = "title"
type = "ByteArray"
key = false

[[members]]
name = "hidden_title"
type = "ByteArray"
key = false

[[members]]
name = "description"
type = "ByteArray"
key = false

[[members]]
name = "hidden_description"
type = "ByteArray"
key = false

[[members]]
name = "image_uri"
type = "ByteArray"
key = false

[[members]]
name = "icon"
type = "felt252"
key = false

[[members]]
name = "time"
type = "u64"
key = false
