kind = "DojoModel"
class_hash = "0x207704d3caf6cb410d35aab29908b36bc45579032daa551ff14a7a4a2234072"
original_class_hash = "0x207704d3caf6cb410d35aab29908b36bc45579032daa551ff14a7a4a2234072"
abi = "manifests/dev/base/abis/models/game_center-Achievement-2d85ca77.json"
tag = "game_center-Achievement"
qualified_path = "achievement::models::index::achievement"
manifest_name = "game_center-Achievement-2d85ca77"

[[members]]
name = "world_address"
type = "felt252"
key = true

[[members]]
name = "namespace"
type = "felt252"
key = true

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "published"
type = "bool"
key = false

[[members]]
name = "whitelisted"
type = "bool"
key = false

[[members]]
name = "karma"
type = "u16"
key = false
