kind = "DojoModel"
class_hash = "0x2dd8fa77be8cd6638d37cc14b6a3cf2b39739789ea1ea1c8259e57ca3d7d74"
original_class_hash = "0x2dd8fa77be8cd6638d37cc14b6a3cf2b39739789ea1ea1c8259e57ca3d7d74"
abi = "manifests/dev/base/abis/models/quest-Achievement-826f4d62.json"
tag = "quest-Achievement"
qualified_path = "quest::models::index::achievement"
manifest_name = "quest-Achievement-826f4d62"

[[members]]
name = "world_address"
type = "felt252"
key = true

[[members]]
name = "namespace"
type = "felt252"
key = true

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "whitelisted"
type = "bool"
key = false

[[members]]
name = "points"
type = "u16"
key = false
