kind = "DojoModel"
class_hash = "0x124c0360a69cd5267343fa457c3abae5ca8882627af7dde5fe354f0e5f1dcb3"
original_class_hash = "0x124c0360a69cd5267343fa457c3abae5ca8882627af7dde5fe354f0e5f1dcb3"
abi = "manifests/dev/base/abis/models/quest-AchievementCompletion-6c59de3b.json"
tag = "quest-AchievementCompletion"
qualified_path = "quest::events::index::achievement_completion"
manifest_name = "quest-AchievementCompletion-6c59de3b"

[[members]]
name = "namespace"
type = "felt252"
key = true

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "player_id"
type = "felt252"
key = true

[[members]]
name = "count"
type = "u32"
key = false

[[members]]
name = "total"
type = "u32"
key = false

[[members]]
name = "time"
type = "u64"
key = false
