# db_dir = "./torii-db"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x2b33bfaf6de21920da455b800547e1bfadabd9e22c299bd08fe42b81451fb02"

[indexing]
events_chunk_size = 1024
blocks_chunk_size = 1024
pending = true
polling_interval = 500
max_concurrent_tasks = 100
world_block = 1278947
contracts = []

[sql]
historical = ["ARCADE-TrophyProgression"]
