kind = "DojoContract"
class_hash = "0x51f892652a06d0701a0d4275ab7dd5ba3c79ef44d91a7083742ce96f96a0f12"
original_class_hash = "0x51f892652a06d0701a0d4275ab7dd5ba3c79ef44d91a7083742ce96f96a0f12"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/game_center-Actions-38eede8c.json"
reads = []
writes = []
init_calldata = []
tag = "game_center-Actions"
systems = [
    "register_game",
    "update_game",
    "publish_game",
    "hide_game",
    "whitelist_game",
    "blacklist_game",
    "remove_game",
    "register_achievement",
    "update_achievement",
    "publish_achievement",
    "hide_achievement",
    "whitelist_achievement",
    "blacklist_achievement",
    "remove_achievement",
]
manifest_name = "game_center-Actions-38eede8c"
